from typing import Any

import pytest
from pytest_factoryboy import register
from rest_framework.test import APIClient

from apps.users.tests.factories import AdminUserFactory, GroupFactory, UserFactory

register(UserFactory)
register(AdminUserFactory)
register(GroupFactory)


@pytest.fixture
def api_client() -> APIClient:
    """
    Fixture for DRF APIClient.
    """
    return APIClient()


@pytest.fixture
def auth_client(api_client: APIClient, user: Any) -> APIClient:
    """
    Fixture for an authenticated API client.
    Uses the 'user' fixture generated by the register(UserFactory) call.
    """
    api_client.force_authenticate(user=user)
    return api_client


@pytest.fixture
def admin_client(api_client: APIClient, admin_user: Any) -> APIClient:
    """
    Fixture for an authenticated API client with a user in the 'admin' group.
    """
    GroupFactory.build(name="superuser").save()
    admin_user.groups.add("superuser")
    api_client.force_authenticate(user=admin_user)
    return api_client
